# Generated by Django 4.2 on 2023-06-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='time_create',
            new_name='dt_create',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='time_update',
            new_name='dt_update',
        ),
        migrations.AddField(
            model_name='category',
            name='dt_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
