# Generated by Django 4.2 on 2023-06-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_time_create_product_dt_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measure',
            field=models.CharField(choices=[('1 Кг', '1 Кг'), ('100 грам', '100 грам'), ('1 Шт', '1 Шт')], max_length=10),
        ),
    ]
