# Generated by Django 4.2.1 on 2023-07-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="measure",
            field=models.CharField(
                choices=[("1 Кг", "1 Кг"), ("100 грам", "100 грам"), ("1 Шт", "1 Шт")],
                max_length=10,
                verbose_name="Вимір",
            ),
        ),
    ]
