# Generated by Django 4.2 on 2023-08-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alt',
            field=models.CharField(default='fish store', max_length=150, verbose_name='alt tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='alt',
            field=models.CharField(default='fish store', max_length=150, verbose_name='alt tag'),
        ),
    ]
